Connection:
	Domain: https://your-v1-domain.com
	Username: YourUsername
    Password: Optional-WillPromptIfOmitted

Criteria:
	Scopes: Project1, Project2
	Timeboxes: Epic, User Story, Defect
	Themes: Theme1, Theme2

Workflow:
  Ready: Ready Queue, Open, (Created)
  Dev: Development
  Dev Done: Dev Done
  Test: Test
  Done: Closed, Cancelled

Attributes:
	Project: Scope
	Range: Timebox
	Theme: Theme
