Connection:
	Domain: https://www6.v1host.com/AutoTrader
	Username: viewmanh
	Password: auctions

Criteria:
	Scopes: Epics
	Timeboxes: Epics Kanban 2015

Workflow:
	Backlog: (None)
	Refinement: Refinement
	Development: Development
	Testing: Testing
	Regression: Regression
	Done: Done

Attributes:
	Project: Scope
	Sprint: Timebox
